version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: gemini_db # Database name
      POSTGRES_USER: app_user # User for the application
      POSTGRES_PASSWORD: app_password # Password for the application
    ports:
      - "5432:5432" # Map to the default postgres port on the host
    volumes:
      - db_gemini_data:/var/lib/postgresql/data
    command: postgres -c password_encryption=md5
  lootbox:
    build:
      context: .
      dockerfile: ./apps/lootbox/Dockerfile
    ports:
      - "3000:3000"
  registry:
    build:
      context: .
      dockerfile: ./apps/registry/Dockerfile
    ports:
      - "8080:8080"
  proxy:
    build:
      context: .
      dockerfile: ./apps/proxy/Dockerfile
    ports:
      - "8000:8000"

volumes:
  db_gemini_data:
