services:
  lootbox:
    build:
      context: .
      dockerfile: ./apps/lootbox/Dockerfile
    ports:
      - "3000:3000"

  registry:
    build:
      context: .
      dockerfile: ./apps/registry/Dockerfile
    ports:
      - "8080:8080"

  proxy:
    build:
      context: .
      dockerfile: ./apps/proxy/Dockerfile
    ports:
      - "8000:8000"

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nonroot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcp-registry
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nonroot -d mcp-registry"]
      interval: 10s
      timeout: 5s
      retries: 5
